import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/app/components/ThemeProvider";

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mulish.variable}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}